version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  web:
    build: ./src/web
    command: python server.py
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
      

  # redis-seed:
  #   build:
  #     context: ./src/redis-seed/
  #   depends_on:
  #     - 'redis'
  #   ports:
  #     - 8080:8080

